services:
  - type: web
    name: book-api
    env: node
    plan: free # Or 'starter' etc.
    buildCommand: 'npm install'
    startCommand: 'node index.js'
    envVars:
      - key: NODE_VERSION
        value: 18 # Specify a Node.js version